# Host:
http://127.0.0.1:7000

# # Query:
#
# # Need to have RESTful method to routes:
# GET /products
#
# # Optional headers specification
# Content-Type: application/json; charset=utf-8
#
# # Register
# POST /auth/register
# {
#   "email": "foo@bar.com",
#   "firstName": "Foo",
#   "lastName": "Bar",
#   "password": "password123"
# }
#
# Login
# POST /auth
# {
#   "email": "foo@bar.com",
#   "password": "password123"
# }

# RESTful with auth:
Accept: */*
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImZvb0BiYXIuY29tIiwiaWF0IjoxNTEyNTM0NjMyLCJleHAiOjE1MTMxMzk0MzIsInN1YiI6IjVhMjc1OTI1YmI1NzRmM2E0ZmFhYzExMiJ9.xE80l4Qz2nFNWrE1diI2i4BIyyHLlHASH6O9qXpeKWQ

GET /products
